import Link from "next/link";

type Guide = { title:string; summary:string; steps:string[]; example:string; limits:string[]; sources:{label:string;href:string}[] };
const guides:Record<string,Guide>={
  takdeukse:{title:"취득세 계산 결과를 읽는 방법",summary:"취득세는 취득 원인, 부동산 종류, 가격, 주택 수와 조정대상지역 여부에 따라 달라집니다. 계산 결과에서는 본세뿐 아니라 지방교육세와 농어촌특별세가 포함됐는지 함께 확인해야 합니다.",steps:["거래 대상과 취득 원인을 선택합니다.","실제 계약금액과 주택 보유 조건을 입력합니다.","본세와 부가세목을 나누어 확인합니다."],example:"예를 들어 같은 가격의 주택도 1주택 일반 취득과 다주택 중과 대상은 결과가 크게 달라질 수 있습니다. 계약 전에는 세대 기준 주택 수와 일시적 2주택 특례 여부를 별도로 확인하세요.",limits:["생애최초·출산가구 등 개별 감면","법인·상속·분양권의 특수 조건","지자체별 사실관계 판단"],sources:[{label:"위택스 지방세 안내",href:"https://www.wetax.go.kr"},{label:"국가법령정보센터 지방세법",href:"https://www.law.go.kr/법령/지방세법"}]},
  yangdo:{title:"양도소득세 계산 전에 확인할 것",summary:"양도세는 매도가격만으로 결정되지 않습니다. 취득가액과 필요경비, 보유·거주기간, 주택 수, 비과세와 장기보유특별공제 조건이 핵심입니다.",steps:["양도가액에서 취득가액과 인정 가능한 필요경비를 뺍니다.","비과세와 장기보유특별공제 가능 여부를 확인합니다.","기본공제 후 과세표준에 세율을 적용합니다."],example:"수리비라고 모두 필요경비가 되는 것은 아닙니다. 자본적 지출에 해당하고 증빙이 있어야 인정되는 항목이 있으므로 영수증과 계약서를 거래 전부터 정리하는 것이 좋습니다.",limits:["1세대 1주택 거주·보유 요건 판정","상속·증여 취득가액과 이월과세","비거주자·해외자산·법인 거래"],sources:[{label:"국세청 양도소득세",href:"https://www.nts.go.kr"},{label:"국가법령정보센터 소득세법",href:"https://www.law.go.kr/법령/소득세법"}]},
  jongbu:{title:"종합부동산세를 추정하는 기준",summary:"종부세는 매매가격이 아니라 과세기준일 현재 보유한 주택의 공시가격 합계와 공제, 공정시장가액비율을 기초로 계산합니다.",steps:["6월 1일 현재 보유 주택의 공시가격을 합산합니다.","납세자 유형에 맞는 기본공제를 적용합니다.","재산세 중복분과 세액공제 가능성을 확인합니다."],example:"공동명의와 단독명의는 공제 방식과 특례 선택에 따라 결과가 다를 수 있습니다. 고령자·장기보유 공제는 1세대 1주택 등 적용 요건을 먼저 확인해야 합니다.",limits:["합산배제 임대주택과 특례","공동명의 1주택 특례 선택","법인 보유 주택"],sources:[{label:"국세청 종합부동산세",href:"https://www.nts.go.kr"},{label:"부동산공시가격 알리미",href:"https://www.realtyprice.kr"}]},
  jeungyese:{title:"증여세 계산의 핵심",summary:"증여세는 받은 재산의 가치에서 관계별 증여재산공제를 차감하고 누진세율을 적용합니다. 같은 사람에게 받은 과거 증여는 일정 기간 합산될 수 있습니다.",steps:["증여일 현재 재산가액을 평가합니다.","증여자와 수증자 관계에 맞는 공제를 적용합니다.","사전증여 합산과 신고세액공제를 확인합니다."],example:"현금뿐 아니라 채무 면제, 저가 양수, 보험금 등 경제적 이익도 증여로 판단될 수 있습니다. 부동산은 시가 인정 범위와 평가기간이 중요합니다.",limits:["재산 평가와 시가 인정 여부","세대생략·부담부증여","창업자금 등 특례"],sources:[{label:"국세청 증여세",href:"https://www.nts.go.kr"},{label:"국가법령정보센터 상속세 및 증여세법",href:"https://www.law.go.kr/법령/상속세및증여세법"}]},
  jaesanse:{title:"재산세 결과 이해하기",summary:"재산세는 매년 과세기준일 현재 소유자를 기준으로 하고, 주택·건축물·토지의 과세표준과 세율이 서로 다릅니다.",steps:["과세 대상의 공시가격 또는 시가표준액을 확인합니다.","대상 유형에 맞는 과세표준 비율을 적용합니다.","재산세와 도시지역분·지방교육세를 구분합니다."],example:"주택 매매일이 6월 1일 전후라면 해당 연도의 납세의무자가 달라질 수 있습니다. 계약서의 세금 정산과 법정 납세의무는 구분해서 이해해야 합니다.",limits:["토지 별도·분리합산 판정","1세대 1주택 특례세율","지자체 도시지역 여부"],sources:[{label:"위택스 지방세 안내",href:"https://www.wetax.go.kr"},{label:"부동산공시가격 알리미",href:"https://www.realtyprice.kr"}]},
  daeul:{title:"상환 방식별 대출비용 비교",summary:"월 납입액만 비교하면 대출비용을 오해하기 쉽습니다. 같은 금리와 기간이라도 원리금균등, 원금균등, 만기일시상환의 현금흐름과 총이자는 다릅니다.",steps:["실제 실행금액과 연이율, 기간을 입력합니다.","월 납입 가능액과 초기 부담을 비교합니다.","총이자와 중도상환 계획까지 함께 검토합니다."],example:"원금균등은 초반 납입액이 크지만 원금이 빠르게 줄어 총이자가 낮아지는 경향이 있습니다. 원리금균등은 월 납입액이 일정해 예산 관리가 편리합니다.",limits:["인지세·보증료·설정비 등 부대비용","변동금리의 향후 변경","중도상환수수료와 우대금리"],sources:[{label:"금융감독원 금융소비자정보",href:"https://fine.fss.or.kr"},{label:"금융상품 한눈에",href:"https://finlife.fss.or.kr"}]},
  jungae:{title:"중개보수 계산 시 주의사항",summary:"중개보수는 거래 종류와 금액에 따른 상한요율 안에서 협의합니다. 월세는 보증금과 월차임을 환산한 거래금액을 사용합니다.",steps:["매매·임대차 등 거래 유형을 구분합니다.","월세는 법정 방식으로 거래금액을 환산합니다.","상한액과 실제 협의액, 부가가치세를 구분합니다."],example:"계산 결과는 받을 수 있는 최대 보수의 기준이며 반드시 그 금액을 지급한다는 의미는 아닙니다. 계약 전 중개사와 보수 및 부가세 포함 여부를 확인하세요.",limits:["주택 외 중개대상물 요율","지역 조례와 개정 시점","중개보조 서비스 비용"],sources:[{label:"한국공인중개사협회",href:"https://www.kar.or.kr"},{label:"국가법령정보센터 공인중개사법",href:"https://www.law.go.kr/법령/공인중개사법"}]},
  pyeong:{title:"평과 제곱미터를 정확히 비교하기",summary:"1평은 약 3.3058㎡입니다. 부동산 광고의 평형과 등기·계약서의 전용면적은 같은 개념이 아니므로 단순 변환값과 면적 종류를 함께 확인해야 합니다.",steps:["계약서에 표시된 면적 단위를 확인합니다.","㎡를 3.3058로 나누어 평으로 환산합니다.","전용·공급·계약면적을 구분해 비교합니다."],example:"전용 84㎡ 아파트가 흔히 33평형으로 불리는 것은 공급면적을 기준으로 한 관행 때문입니다. 전용 84㎡ 자체는 약 25.4평입니다.",limits:["공용면적 포함 여부","오피스텔·상가의 계약면적","광고상 평형 표기"],sources:[{label:"국가법령정보센터 계량에 관한 법률",href:"https://www.law.go.kr/법령/계량에관한법률"}]},
  imdae:{title:"임대수익률을 현실적으로 계산하기",summary:"표면수익률보다 실제 투자금과 공실, 세금, 수선비를 반영한 순수익률이 투자 판단에 더 유용합니다.",steps:["매입가에서 대출을 제외한 실투자금을 구합니다.","연 임대수입에서 반복 비용을 차감합니다.","공실과 금리 변화에 따른 민감도를 비교합니다."],example:"월세가 같아도 취득비용, 관리비 부담, 대출 비율이 다르면 순수익률이 크게 달라집니다. 낙관·기준·보수 시나리오를 각각 계산해 보세요.",limits:["향후 매각차익과 양도세","예상하지 못한 대수선비","임대소득 종합과세"],sources:[{label:"국토교통부 실거래가 공개시스템",href:"https://rt.molit.go.kr"},{label:"국세청 임대소득 안내",href:"https://www.nts.go.kr"}]},
  jeonwolse:{title:"전세와 월세를 같은 기준으로 비교",summary:"전월세 전환율은 보증금을 월세로 바꿀 때 적용하는 연간 비율입니다. 법정 상한과 실제 시장 전환율은 다를 수 있습니다.",steps:["기존·변경 보증금의 차액을 구합니다.","적용 전환율을 연간 금액으로 계산합니다.","월 단위로 나누어 월세 증감액을 확인합니다."],example:"보증금을 낮추고 월세를 높일 때는 단순 월세뿐 아니라 보증금 마련을 위한 대출이자, 예금수익, 계약 안정성을 함께 비교해야 합니다.",limits:["계약갱신 시 법정 상한 적용","관리비와 별도 사용료","지역별 시장 전환율"],sources:[{label:"국토교통부 주택임대차",href:"https://www.molit.go.kr"},{label:"국가법령정보센터 주택임대차보호법",href:"https://www.law.go.kr/법령/주택임대차보호법"}]},
  yeonbong:{title:"연봉과 실수령액의 차이",summary:"연봉 계약금액에서 4대 보험과 근로소득 원천징수세액 등을 공제하면 실제 월 수령액이 됩니다. 비과세 급여와 부양가족 조건에 따라 결과가 달라집니다.",steps:["연봉에 포함된 상여와 비과세 급여를 구분합니다.","사회보험과 소득세 공제액을 확인합니다.","월·연간 실수령액과 공제율을 비교합니다."],example:"같은 연봉이라도 식대 등 비과세 항목, 부양가족, 회사의 상여 지급 방식에 따라 매월 지급액이 다를 수 있으며 연말정산에서 최종 세액이 조정됩니다.",limits:["회사별 급여·상여 지급 방식","개인별 연말정산 공제","보험료 상·하한과 중도 입사"],sources:[{label:"국세청 근로소득",href:"https://www.nts.go.kr"},{label:"4대사회보험 정보연계센터",href:"https://www.4insure.or.kr"}]}
};

export default function CalculatorGuide({slug}:{slug:string}){const g=guides[slug];if(!g)return null;return <section className="content-container mt-10"><div className="border-t border-slate-200 pt-12"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">How it works</p><h2 className="mt-2 text-[1.65rem] font-extrabold tracking-[-.03em] text-slate-950">{g.title}</h2></div><span className="w-fit rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-500">최근 검토 2026.08.17</span></div><p className="mt-5 max-w-2xl text-sm leading-7 text-slate-600">{g.summary}</p>
  <div className="mt-8 grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><div className="surface-card rounded-2xl p-6"><h3 className="text-sm font-bold text-slate-900">계산 순서</h3><ol className="mt-4 space-y-4">{g.steps.map((s,i)=><li key={s} className="flex gap-3 text-sm leading-6 text-slate-600"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-blue-50 text-[11px] font-bold text-blue-700">{i+1}</span>{s}</li>)}</ol><div className="mt-6 rounded-xl bg-blue-50 p-4"><p className="text-xs font-bold text-blue-800">실무 예시</p><p className="mt-2 text-sm leading-6 text-blue-900/75">{g.example}</p></div></div><div className="surface-card rounded-2xl p-6"><h3 className="text-sm font-bold text-slate-900">별도 확인이 필요한 항목</h3><ul className="mt-4 space-y-3">{g.limits.map(x=><li key={x} className="flex gap-2 text-sm text-slate-600"><span className="mt-1 text-amber-500">◆</span>{x}</li>)}</ul><h3 className="mt-7 text-sm font-bold text-slate-900">주요 공식 자료</h3><div className="mt-3 flex flex-wrap gap-2">{g.sources.map(s=><a key={s.href} href={s.href} target="_blank" rel="noreferrer" className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600 hover:border-blue-300 hover:text-blue-700">{s.label} ↗</a>)}</div><Link href="/methodology" className="mt-5 block text-xs font-bold text-blue-600">전체 계산 방법론 보기 →</Link></div></div></div></section>}
